# Generated by Django 2.2.4 on 2020-08-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coa',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='phototype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phototype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
    ]
