# Generated by Django 2.2.4 on 2020-08-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_cat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
