# Generated by Django 2.2.4 on 2020-08-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
