# Generated by Django 2.2.4 on 2020-08-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
