# Generated by Django 3.0.8 on 2020-10-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200828_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders_placed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_placed_by', to='main.Order'),
        ),
    ]
